[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "libdrm",
  "libX11",
  "libXcomposite",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXrandr",
  "mesa",
  "pango",
  "cairo",
  "alsa-lib",
  "xorg.libxcb",
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[start]
cmd = "PUPPETEER_EXECUTABLE_PATH=$(which chromium) node src/index.js"
